name: libvmi
adopt-info: libvmi
summary: LibVMI
description: |
    LibVMI is a C library with Python bindings that makes it easy to monitor the low-level details of
    a running virtual machine by viewing its memory, trapping on hardware events, and accessing the
    vCPU registers. This is called virtual machine introspection.

grade: devel
confinement: devmode
architectures:
  - build-on: [amd64, i386, armhf, arm64]

parts:
  libvmi:
    source: .
    build-packages:
        - autoconf-archive
        - flex
        - bison
        - libjson-c-dev
        - libxen-dev
        - libfuse-dev
        - build-essential
        - pkg-config
        - libglib2.0-dev
    stage-packages:
        - libjson-c-dev
        - libglib2.0-0
    plugin: autotools
    override-build: |
      autoreconf -vif
      ./configure --disable-kvm --prefix=${SNAPCRAFT_PART_INSTALL}
      make
      # override pkg-config prefix
      sed -i "1s/.*/prefix=\/snap\/${SNAPCRAFT_PROJECT_NAME}\/current" libvmi.pc
      make install
      rm -f ${SNAPCRAFT_PART_INSTALL}/lib/libvmi.la
      # set version
      VERSION="$(grep AC_INIT configure.ac | sed 's/^.*\[//;s/\].*$//')"
      echo "setting version to $VERSION"
      snapcraftctl set-version $VERSION
